<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageVersion Include="ktsu.Coder" Version="3.18.14" />
    <PackageVersion Include="ktsu.CodeBlocker" Version="2.3.4" />
    <PackageVersion Include="ktsu.DeepClone" Version="2.4.4" />
    <PackageVersion Include="ktsu.Extensions" Version="1.9.2" />
    <PackageVersion Include="ktsu.ForceDirectedLayout" Version="3.64.0" />
    <PackageVersion Include="ktsu.FuzzySearch" Version="1.4.1" />
    <PackageVersion Include="ktsu.ImGui.Styler" Version="3.64.0" />
    <PackageVersion Include="ktsu.ThemeProvider" Version="3.1.1" />
    <PackageVersion Include="ktsu.IntervalAction" Version="1.6.0" />
    <PackageVersion Include="ktsu.Keybinding" Version="2.1.6" />
    <PackageVersion Include="ktsu.UndoRedo.Core" Version="1.1.4" />
    <PackageVersion Include="ktsu.RoundTripStringJsonConverter" Version="1.0.75" />
    <PackageVersion Include="ktsu.Semantics.Quantities" Version="5.11.3" />
    <PackageVersion Include="ktsu.Semantics.Strings" Version="5.11.3" />
    <PackageVersion Include="ktsu.Semantics.Paths" Version="5.11.3" />
    <PackageVersion Include="ktsu.ImGui.App" Version="3.64.0" />
    <PackageVersion Include="ktsu.ImGui.App.Testing" Version="3.64.0" />
    <PackageVersion Include="ktsu.ImGui.Popups" Version="3.64.0" />
    <PackageVersion Include="ktsu.ImGui.Probes" Version="3.64.0" />
    <PackageVersion Include="ktsu.ImGui.Widgets" Version="3.64.0" />
    <PackageVersion Include="ktsu.ImGui.NodeEditor" Version="3.38.5" />
    <PackageVersion Include="ktsu.NodeGraph" Version="1.0.0" />
    <PackageVersion Include="ktsu.AppDataStorage" Version="1.18.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Microsoft.SourceLink.AzureRepos.Git" Version="10.0.401" />
    <PackageVersion Include="Polyfill" Version="11.4.3" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.3.0" />
  </ItemGroup>
</Project>
