// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Editor.UITests.Gallery;

using System.Collections.Generic;
using System.Text;

/// <summary>Writes the gallery's <c>README.md</c>, which captions each picture.</summary>
internal static class GalleryIndex
{
	/// <summary>Renders the index for the given entries, in catalog order.</summary>
	internal static string Render(IReadOnlyList<GalleryEntry> entries)
	{
		StringBuilder text = new();
		text.Append("# Editor gallery\n\n");
		text.Append("<!-- Generated by tests/Schema.Editor.UITests/Gallery. Edit GalleryCatalog.cs, not this file. -->\n\n");
		text.Append("The Schema editor as it draws today, working on a small sample schema for a game, staged and photographed headlessly by the UI test harness. ");
		text.Append("The pictures are regenerated on every successful build of `main`, so they show the current editor.\n\n");

		foreach (GalleryEntry entry in entries)
		{
			text.Append("## ").Append(entry.Name).Append("\n\n");
			text.Append(entry.Description).Append("\n\n");
			text.Append("![").Append(entry.Name).Append("](").Append(entry.Slug).Append(".png)\n\n");
		}

		return text.ToString();
	}
}
