// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Cpp.Test;

using ktsu.Schema.Models;
using ktsu.Schema.Models.Names;
using ktsu.Schema.Models.Types;
using ktsu.Semantics.Strings;

using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Builds the interface from Holotype's <c>docs/generated-cpp-target.md</c> as a schema and checks
/// that this generator emits the header an implementation is written against.
/// </summary>
/// <remarks>
/// §3's point is what is <em>not</em> in the signatures. Four conventions the schema holds globally
/// carry the weight that ownership, lifetime and error annotations carry elsewhere, and each has
/// exactly one C++ spelling. This test is what says the spelling is right.
/// <para>
/// Two differences from the document. It writes <c>holo::Result&lt;BodyHandle&gt;</c>, using a
/// named alias for the handle and leaving the error type implicit; the schema spells the handle
/// structurally and now names the error enum, so the generated return type says both. And
/// <c>find</c> is <c>const</c> there and is not here - see
/// <see cref="AQueryCannotYetSayItLeavesTheReceiverUnchanged"/>, which is a gap in the schema
/// rather than in this generator.
/// </para>
/// </remarks>
[TestClass]
public sealed class ExemplarInterfaceTests
{
	/// <summary>The document's §3, as a whole header.</summary>
	private const string ExpectedInterface =
		"""
		// Generated by ktsu.Schema. Do not edit.
		//
		// Source: the schema
		//
		// Editing this file is editing the wrong thing: it is derived from the schema,
		// and the next build overwrites it. Change the schema instead.

		#pragma once

		#include <optional>
		#include <span>

		#include "EntityId.gen.hpp"
		#include "Position.gen.hpp"
		#include "RigidBody.gen.hpp"
		#include "Seconds.gen.hpp"
		#include "Velocity.gen.hpp"
		#include "holotype/core/handle.hpp"
		#include "holotype/core/result.hpp"

		namespace holo
		{

		/// The simulation the physics system drives.
		class IPhysicsWorld
		{
		public:
		    IPhysicsWorld() = default;
		    IPhysicsWorld(const IPhysicsWorld&) = delete;
		    IPhysicsWorld& operator=(const IPhysicsWorld&) = delete;
		    virtual ~IPhysicsWorld() = default;

		    /// Advance the simulation by one step.
		    virtual void step(Seconds dt) = 0;

		    /// Create a body. Fails if the world is at capacity.
		    [[nodiscard]] virtual holo::Result<holo::Handle<RigidBody>, ErrorCode> spawn(const RigidBody& body) = 0;

		    /// Integrate velocities into positions.
		    virtual void integrate(std::span<const Velocity> velocities, std::span<Position> positions) = 0;

		    /// The body for an entity, if it has one.
		    [[nodiscard]] virtual std::optional<RigidBody> find(EntityId entity) = 0;
		};

		}  // namespace holo
		""";

	/// <summary>
	/// The generated header is the one the document specifies.
	/// </summary>
	[TestMethod]
	public void GeneratesTheInterfaceTheDocumentSpecifies() =>
		Assert.AreEqual(
			ExpectedInterface.ReplaceLineEndings("\n").TrimEnd(),
			Generate()["IPhysicsWorld.gen.hpp"].ReplaceLineEndings("\n").TrimEnd());

	/// <summary>
	/// Direction on a Span describes the elements, not the view. That is what makes a system's
	/// signature an ordinary one rather than something needing a concept of its own.
	/// </summary>
	[TestMethod]
	public void DirectionOnASpanDescribesTheElements()
	{
		string code = Generate()["IPhysicsWorld.gen.hpp"];

		Assert.Contains("std::span<const Velocity> velocities", code, StringComparison.Ordinal);
		Assert.Contains("std::span<Position> positions", code, StringComparison.Ordinal);
	}

	/// <summary>
	/// A value worth not copying is borrowed; a value that fits in a register is passed whole.
	/// </summary>
	[TestMethod]
	public void SmallValuesArePassedWholeAndLargeOnesBorrowed()
	{
		string code = Generate()["IPhysicsWorld.gen.hpp"];

		Assert.Contains("const RigidBody& body", code, StringComparison.Ordinal);
		Assert.Contains("(EntityId entity)", code, StringComparison.Ordinal);
		Assert.Contains("(Seconds dt)", code, StringComparison.Ordinal);
	}

	/// <summary>
	/// The error a failure carries comes from the schema, once, rather than from the signature.
	/// </summary>
	[TestMethod]
	public void TheErrorTypeComesFromTheSchema()
	{
		string code = Generate()["IPhysicsWorld.gen.hpp"];

		Assert.Contains("holo::Result<holo::Handle<RigidBody>, ErrorCode>", code, StringComparison.Ordinal);
	}

	/// <summary>
	/// A target that has no fallible return is told which option to set, rather than handed a
	/// header that will not compile.
	/// </summary>
	[TestMethod]
	public void ATargetWithoutAResultTypeIsRefusedByName()
	{
		Models.Schema schema = ExemplarSchema();

		CppGenerationException refused = Assert.ThrowsExactly<CppGenerationException>(() =>
			new CppCodeGenerator(new CppGeneratorOptions()).Generate(
				schema,
				schema.GetCodeGenerator("Cpp".As<CodeGeneratorName>())!));

		Assert.Contains("Result", refused.Message, StringComparison.Ordinal);
		Assert.Contains(nameof(CppGeneratorOptions.Result), refused.Message, StringComparison.Ordinal);
	}

	/// <summary>
	/// The document writes <c>find</c> as <c>const</c>. The schema has no way to say that a call
	/// leaves the receiver unchanged, so the generated declaration is not const.
	/// </summary>
	/// <remarks>
	/// A gap in <c>ktsu.Schema</c> rather than in this generator, and the last one §3 exposes: the
	/// four conventions cover whether an <em>argument</em> is read-only and say nothing about the
	/// receiver. The AST is ready for it - <c>FunctionDeclaration.IsReadOnly</c> is what emits the
	/// trailing const - so closing it is a property on <c>SchemaFunction</c> and one line here.
	/// This test exists so the gap is asserted rather than merely absent, and fails when it is
	/// closed.
	/// </remarks>
	[TestMethod]
	public void AQueryCannotYetSayItLeavesTheReceiverUnchanged()
	{
		string code = Generate()["IPhysicsWorld.gen.hpp"];

		Assert.Contains("find(EntityId entity) = 0;", code, StringComparison.Ordinal);
		Assert.DoesNotContain("find(EntityId entity) const", code, StringComparison.Ordinal);
	}

	private static IReadOnlyDictionary<string, string> Generate()
	{
		Models.Schema schema = ExemplarSchema();
		CppGeneratorOptions options = new()
		{
			Handle = new CppTypeSpelling("holo::Handle", "holotype/core/handle.hpp"),
			Result = new CppTypeSpelling("holo::Result", "holotype/core/result.hpp"),
		};

		return new CppCodeGenerator(options).Generate(schema, schema.GetCodeGenerator("Cpp".As<CodeGeneratorName>())!);
	}

	/// <summary>
	/// The schema a person would write to get the document's third section.
	/// </summary>
	private static Models.Schema ExemplarSchema()
	{
		Models.Schema schema = new();

		SchemaCodeGenerator configuration = schema.AddCodeGenerator("Cpp".As<CodeGeneratorName>())!;
		configuration.Language = CppCodeGenerator.LanguageId.As<LanguageName>();
		configuration.Namespace = "holo".As<CodeNamespace>();

		schema.AddEnum("ErrorCode".As<EnumName>())!.TryAddValue("OutOfCapacity".As<EnumValueName>());
		schema.ErrorType = "ErrorCode".As<EnumName>();

		foreach (string over in (string[])["Seconds", "Velocity", "Position", "EntityId"])
		{
			schema.AddSemanticType(over.As<SemanticTypeName>())!.SetUnderlyingType(new Float());
		}

		schema.AddClass("RigidBody".As<ClassName>())!
			.AddMember("Mass".As<MemberName>())!
			.SetType(new Float());

		SchemaInterface world = schema.AddInterface("IPhysicsWorld".As<InterfaceName>())!;
		world.Description = "The simulation the physics system drives.".As<SchemaChildDescription>();

		SchemaFunction step = world.AddFunction("Step".As<FunctionName>())!;
		step.Description = "Advance the simulation by one step.".As<SchemaChildDescription>();
		step.SetReturnType(new Void());
		step.AddParameter("dt".As<ParameterName>())!.SetType(Named("Seconds"));

		SchemaFunction spawn = world.AddFunction("Spawn".As<FunctionName>())!;
		spawn.Description = "Create a body. Fails if the world is at capacity.".As<SchemaChildDescription>();
		spawn.SetReturnType(new Result
		{
			ElementType = new Handle { ElementType = Body() },
		});
		spawn.AddParameter("body".As<ParameterName>())!.SetType(Body());

		SchemaFunction integrate = world.AddFunction("Integrate".As<FunctionName>())!;
		integrate.Description = "Integrate velocities into positions.".As<SchemaChildDescription>();
		integrate.SetReturnType(new Void());
		integrate.AddParameter("velocities".As<ParameterName>())!.SetType(new Span { ElementType = Named("Velocity") });

		SchemaParameter positions = integrate.AddParameter("positions".As<ParameterName>())!;
		positions.SetType(new Span { ElementType = Named("Position") });
		positions.Direction = ParameterDirection.Out;

		SchemaFunction find = world.AddFunction("Find".As<FunctionName>())!;
		find.Description = "The body for an entity, if it has one.".As<SchemaChildDescription>();
		find.SetReturnType(new Optional { ElementType = Body() });
		find.AddParameter("entity".As<ParameterName>())!.SetType(Named("EntityId"));

		return schema;
	}

	private static Models.Types.Object Body() => new() { ClassName = "RigidBody".As<ClassName>() };

	private static Semantic Named(string semanticType) =>
		new() { SemanticTypeName = semanticType.As<SemanticTypeName>() };
}
