// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Cpp.Test;

using ktsu.Schema.Cpp;
using ktsu.Schema.Models;
using ktsu.Schema.Models.Metadata;
using ktsu.Schema.Models.Names;
using ktsu.Schema.Models.Types;
using ktsu.Semantics.Strings;

using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Builds the component from Holotype's <c>docs/generated-cpp-target.md</c> as a schema and checks
/// that this generator emits the header that document specifies.
/// </summary>
/// <remarks>
/// This is the acceptance test for the move the document describes. <c>ktsu.Coder</c> already has
/// an identical test that builds the same header as an AST by hand; this one starts one step
/// further back, from the <c>.schema.json</c> a person would actually write, and so is what says
/// the schema can describe the thing at all.
/// <para>
/// Three differences from the document are deliberate and are the subject of their own assertions
/// below rather than being quietly absorbed:
/// </para>
/// <para>
/// <b>The enum is at namespace scope in its own header</b> rather than nested inside the struct.
/// The document nests it, on the grounds that two components in one file might both declare a
/// <c>kind</c> - which was true of the TOML front end, where an enum belonged to the component
/// that declared it. In <c>ktsu.Schema</c> an enum is a top-level element any class may name, so
/// nesting it in the one class that uses it today would move the type the moment a second class
/// used it, breaking every caller that spelled <c>RigidBody::BodyKind</c> because of an edit
/// somewhere else. Field offsets are unaffected, so <c>generated_compiles.cpp</c> still holds.
/// </para>
/// <para>
/// <b>The banner names this generator</b> rather than <c>holo_schemac</c>, which is the tool being
/// replaced. <see cref="CppGeneratorOptions.GeneratedBy"/> is what a target sets to say otherwise.
/// </para>
/// <para>
/// <b>Indentation is spaces where the document has tabs</b>, which is a setting of the writer
/// rather than anything the schema or the AST decides - Holotype's own <c>.clang-format</c>
/// converts it on the way past.
/// </para>
/// </remarks>
[TestClass]
public sealed class ExemplarComponentTests
{
	/// <summary>The document's first section, less its nested enum, with this generator's banner.</summary>
	private const string ExpectedComponent =
		"""
		// Generated by ktsu.Schema. Do not edit.
		//
		// Source: the schema
		//
		// Editing this file is editing the wrong thing: it is derived from the schema,
		// and the next build overwrites it. Change the schema instead.

		#pragma once

		#include <type_traits>

		#include "BodyKind.gen.hpp"
		#include "holotype/core/units.hpp"
		#include "holotype/core/vector.hpp"

		namespace holo::components
		{

		/// Physical state integrated by the physics system each frame.
		struct RigidBody
		{
		    /// Linear velocity in world space.
		    /// unit: m/s
		    /// interpolated between states
		    /// network: quantised to 0.01, delta encoded
		    holo::Vector3<holo::MetresPerSecond> velocity{};

		    /// unit: kg
		    /// range: [0.001, 1000000]
		    holo::Kilograms mass = holo::Kilograms{ 1.0f };

		    /// unit: rad
		    /// range: [0, 6.2831853] (wraps)
		    /// network: quantised to 0.001
		    /// editor: dial
		    holo::Radians heading{};

		    /// unit: 1
		    /// range: [0, 1]
		    holo::Scalar restitution = holo::Scalar{ 0.5f };

		    BodyKind body_kind = BodyKind::Dynamic;
		};

		static_assert(std::is_trivially_copyable_v<RigidBody>,
		    "RigidBody must be trivially copyable: it crosses a language boundary and the wire as bytes");
		static_assert(std::is_standard_layout_v<RigidBody>,
		    "RigidBody must be standard layout for its field offsets to be stable");

		}  // namespace holo::components
		""";

	/// <summary>The enum the document nests, in the file this generator gives it.</summary>
	private const string ExpectedEnum =
		"""
		// Generated by ktsu.Schema. Do not edit.
		//
		// Source: the schema
		//
		// Editing this file is editing the wrong thing: it is derived from the schema,
		// and the next build overwrites it. Change the schema instead.

		#pragma once

		#include <cstdint>

		namespace holo::components
		{

		enum class BodyKind : std::uint8_t
		{
		    Static,
		    Kinematic,
		    Dynamic,
		};

		}  // namespace holo::components
		""";

	/// <summary>
	/// The generated header is the one the document specifies.
	/// </summary>
	[TestMethod]
	public void GeneratesTheComponentTheDocumentSpecifies() =>
		AssertGenerated("RigidBody.gen.hpp", ExpectedComponent);

	/// <summary>
	/// The enum is a header of its own, and the component includes it.
	/// </summary>
	[TestMethod]
	public void GeneratesTheEnumAsAHeaderOfItsOwn() =>
		AssertGenerated("BodyKind.gen.hpp", ExpectedEnum);

	/// <summary>
	/// Declaration order is struct layout, so it is the one thing about the output that is not
	/// cosmetic.
	/// </summary>
	/// <remarks>
	/// Alphabetically these would be body_kind, heading, mass, restitution, velocity. Holotype's
	/// schema notes record catching exactly that in a parser whose tables were sorted, and record
	/// why it matters: reordering a field silently changes the binary layout of every save file
	/// and every packet carrying the component.
	/// </remarks>
	[TestMethod]
	public void KeepsMembersInDeclarationOrder()
	{
		string code = Generate()["RigidBody.gen.hpp"];

		int previous = -1;
		foreach (string name in (string[])["velocity", "mass", "heading", "restitution", "body_kind"])
		{
			int position = code.IndexOf($" {name}", StringComparison.Ordinal);

			Assert.IsGreaterThan(previous, position, $"{name} is out of declaration order");
			previous = position;
		}
	}

	/// <summary>
	/// The two assertions come from the schema's own promise rather than from the generator's
	/// opinion: a class that does not say it travels as bytes gets neither.
	/// </summary>
	[TestMethod]
	public void TheAssertionsComeFromTheSchemasPromise()
	{
		Models.Schema schema = ExemplarSchema();
		schema.GetClass("RigidBody".As<ClassName>())!.TravelsAsBytes = false;

		string code = Generate(schema)["RigidBody.gen.hpp"];

		Assert.DoesNotContain("static_assert", code, StringComparison.Ordinal);
		Assert.DoesNotContain("<type_traits>", code, StringComparison.Ordinal);
	}

	private static void AssertGenerated(string file, string expected) =>
		Assert.AreEqual(
			expected.ReplaceLineEndings("\n").TrimEnd(),
			Generate()[file].ReplaceLineEndings("\n").TrimEnd());

	private static IReadOnlyDictionary<string, string> Generate() => Generate(ExemplarSchema());

	private static IReadOnlyDictionary<string, string> Generate(Models.Schema schema)
	{
		SchemaCodeGenerator configuration = schema.GetCodeGenerator("Cpp".As<CodeGeneratorName>())!;
		return new CppCodeGenerator(HolotypeOptions).Generate(schema, configuration);
	}

	/// <summary>
	/// What Holotype tells the generator: the three types its core supplies that standard C++ has
	/// no answer for, and the units it already declares by hand.
	/// </summary>
	private static CppGeneratorOptions HolotypeOptions => new()
	{
		Vector2 = new CppTypeSpelling("holo::Vector2", "holotype/core/vector.hpp"),
		Vector3 = new CppTypeSpelling("holo::Vector3", "holotype/core/vector.hpp"),
		Vector4 = new CppTypeSpelling("holo::Vector4", "holotype/core/vector.hpp"),
		Handle = new CppTypeSpelling("holo::Handle", "holotype/core/handle.hpp"),
		Result = new CppTypeSpelling("holo::Result", "holotype/core/result.hpp"),
		ExistingTypes = new Dictionary<string, CppTypeSpelling>(StringComparer.Ordinal)
		{
			["MetresPerSecond"] = new("holo::MetresPerSecond", "holotype/core/units.hpp"),
			["Kilograms"] = new("holo::Kilograms", "holotype/core/units.hpp"),
			["Radians"] = new("holo::Radians", "holotype/core/units.hpp"),
			["Scalar"] = new("holo::Scalar", "holotype/core/units.hpp"),
			["Seconds"] = new("holo::Seconds", "holotype/core/units.hpp"),
		},
	};

	/// <summary>
	/// The schema a person would write to get the document's first section.
	/// </summary>
	private static Models.Schema ExemplarSchema()
	{
		Models.Schema schema = new();

		SchemaCodeGenerator configuration = schema.AddCodeGenerator("Cpp".As<CodeGeneratorName>())!;
		configuration.Language = CppCodeGenerator.LanguageId.As<LanguageName>();
		configuration.Namespace = "holo::components".As<CodeNamespace>();

		foreach (string unit in (string[])["MetresPerSecond", "Kilograms", "Radians", "Scalar", "Seconds"])
		{
			schema.AddSemanticType(unit.As<SemanticTypeName>())!.SetUnderlyingType(new Float());
		}

		SchemaEnum bodyKind = schema.AddEnum("BodyKind".As<EnumName>())!;
		bodyKind.TryAddValue("Static".As<EnumValueName>());
		bodyKind.TryAddValue("Kinematic".As<EnumValueName>());
		bodyKind.TryAddValue("Dynamic".As<EnumValueName>());

		SchemaClass rigidBody = schema.AddClass("RigidBody".As<ClassName>())!;
		rigidBody.Description = "Physical state integrated by the physics system each frame.".As<SchemaChildDescription>();
		rigidBody.TravelsAsBytes = true;

		SchemaMember velocity = rigidBody.AddMember("Velocity".As<MemberName>())!;
		velocity.Description = "Linear velocity in world space.".As<SchemaChildDescription>();
		velocity.SetType(new Vector3 { ElementType = Named("MetresPerSecond") });
		velocity.Unit = "m/s".As<UnitSymbol>();
		velocity.Interpolation = Interpolation.Linear;
		velocity.Network = new MemberNetwork { Quantise = 0.01, Delta = true };

		SchemaMember mass = rigidBody.AddMember("Mass".As<MemberName>())!;
		mass.SetType(Named("Kilograms"));
		mass.Unit = "kg".As<UnitSymbol>();
		mass.Range = new MemberRange { Minimum = 0.001, Maximum = 1000000 };
		mass.DefaultValue = new NumberDefault { Value = 1.0 };

		SchemaMember heading = rigidBody.AddMember("Heading".As<MemberName>())!;
		heading.SetType(Named("Radians"));
		heading.Unit = "rad".As<UnitSymbol>();
		heading.Range = new MemberRange { Minimum = 0, Maximum = 6.2831853, Wrap = true };
		heading.Network = new MemberNetwork { Quantise = 0.001 };
		heading.Editor = "dial".As<EditorHint>();

		SchemaMember restitution = rigidBody.AddMember("Restitution".As<MemberName>())!;
		restitution.SetType(Named("Scalar"));
		restitution.Unit = "1".As<UnitSymbol>();
		restitution.Range = new MemberRange { Minimum = 0, Maximum = 1 };
		restitution.DefaultValue = new NumberDefault { Value = 0.5 };

		SchemaMember kind = rigidBody.AddMember("BodyKind".As<MemberName>())!;
		kind.SetType(new Models.Types.Enum { EnumName = "BodyKind".As<EnumName>() });
		kind.DefaultValue = new TextDefault { Value = "Dynamic" };

		return schema;
	}

	private static Semantic Named(string semanticType) =>
		new() { SemanticTypeName = semanticType.As<SemanticTypeName>() };
}
