// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Cpp.Test;

using ktsu.Schema.Models;
using ktsu.Schema.Models.Names;
using ktsu.Schema.Models.Types;
using ktsu.Semantics.Strings;

using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Builds the semantic types from Holotype's <c>docs/generated-cpp-target.md</c> as a schema and
/// checks that this generator emits the shim that document specifies.
/// </summary>
/// <remarks>
/// An entity id is a number and so is a texture id, and adding one to the other is nonsense that
/// compiles. The generated class is what makes it not compile, and §2 of the document is what it
/// has to look like.
/// <para>
/// Four differences from the document, each deliberate:
/// </para>
/// <para>
/// <b>The banner and the namespace.</b> The document's §2 is a fragment - a declaration quoted on
/// its own - and this generator emits whole headers.
/// </para>
/// <para>
/// <b>"a bare value" and "getting the value back out"</b> where the document says "number". The
/// document's example is over a number; a semantic type is not, so the generated sentence has to
/// be true of a shim over anything its representation can be.
/// </para>
/// <para>
/// <b>The accessor is a braced block</b> where the document writes <c>{ return value_; }</c> on the
/// signature's line. That is <c>ktsu.Coder</c>'s choice rather than this one, and it is recorded
/// there too: clang-format run over each leaves both exactly as written, so copying the inline
/// style would mean a generator guessing at when a body is short enough to fold.
/// </para>
/// <para>
/// <b>Indentation is spaces</b>, which Holotype's own <c>.clang-format</c> converts on the way
/// past.
/// </para>
/// </remarks>
[TestClass]
public sealed class ExemplarSemanticTypeTests
{
	/// <summary>The document's §2, as a whole header.</summary>
	private const string ExpectedEntityId =
		"""
		// Generated by ktsu.Schema. Do not edit.
		//
		// Source: the schema
		//
		// Editing this file is editing the wrong thing: it is derived from the schema,
		// and the next build overwrites it. Change the schema instead.

		#pragma once

		#include <cstdint>
		#include <type_traits>

		namespace holo
		{

		/// A live entity. Distinct from every other identifier stored as a number.
		class EntityId
		{
		public:
		    using underlying = std::int64_t;

		    constexpr EntityId() noexcept = default;

		    /// Explicit: a bare value never becomes an EntityId by accident.
		    explicit constexpr EntityId(underlying value) noexcept
		        : value_(value)
		    {
		    }

		    /// Named, because getting the value back out is a decision too.
		    [[nodiscard]] constexpr underlying value() const noexcept
		    {
		        return value_;
		    }

		    [[nodiscard]] friend constexpr bool operator==(EntityId, EntityId) noexcept = default;
		    [[nodiscard]] friend constexpr auto operator<=>(EntityId, EntityId) noexcept = default;

		private:
		    underlying value_{};
		};

		static_assert(std::is_trivially_copyable_v<EntityId>,
		    "EntityId must be trivially copyable: it appears in components");
		static_assert(std::is_standard_layout_v<EntityId>,
		    "EntityId must be standard layout for its field offsets to be stable");

		}  // namespace holo
		""";

	/// <summary>
	/// The generated shim is the one the document specifies.
	/// </summary>
	[TestMethod]
	public void GeneratesTheSemanticTypeTheDocumentSpecifies() =>
		Assert.AreEqual(
			ExpectedEntityId.ReplaceLineEndings("\n").TrimEnd(),
			Generate()["EntityId.gen.hpp"].ReplaceLineEndings("\n").TrimEnd());

	/// <summary>
	/// The asymmetry the schema holds - implicit up, explicit down - is spelled as a conversion
	/// operator in one direction and a named factory in the other, which is how C++ says it.
	/// </summary>
	[TestMethod]
	public void RefinementWidensImplicitlyAndNarrowsExplicitly()
	{
		string code = Generate()["Weight.gen.hpp"].ReplaceLineEndings("\n");

		Assert.Contains("using refines = ForceMagnitude;", code, StringComparison.Ordinal);
		Assert.Contains(
			"[[nodiscard]] constexpr operator ForceMagnitude() const noexcept",
			code,
			StringComparison.Ordinal);
		Assert.Contains(
			"[[nodiscard]] static constexpr Weight from(ForceMagnitude value) noexcept",
			code,
			StringComparison.Ordinal);
	}

	/// <summary>
	/// A refining type is stored as whatever the chain ends at, not as the type it refines - which
	/// is what makes the two the same size and the widening free.
	/// </summary>
	[TestMethod]
	public void ARefiningTypeIsStoredAsWhatTheChainEndsAt()
	{
		string code = Generate()["Weight.gen.hpp"];

		Assert.Contains("using underlying = float;", code, StringComparison.Ordinal);
		Assert.Contains("#include \"ForceMagnitude.gen.hpp\"", code, StringComparison.Ordinal);
	}

	/// <summary>
	/// A member's unit is a comment on the member; a semantic type's is a comment on the type,
	/// because for some values that fact belongs to the type rather than to any one use.
	/// </summary>
	[TestMethod]
	public void ASemanticTypesOwnMetadataIsWrittenAboveIt()
	{
		string code = Generate()["ForceMagnitude.gen.hpp"].ReplaceLineEndings("\n");

		Assert.Contains("/// The magnitude of a force.\n/// unit: N\nclass ForceMagnitude", code, StringComparison.Ordinal);
	}

	/// <summary>
	/// A type the target already declares by hand is not generated a second time beside the one
	/// that exists.
	/// </summary>
	[TestMethod]
	public void ATypeTheTargetAlreadyHasIsNotGenerated()
	{
		IReadOnlyDictionary<string, string> files = Generate(new CppGeneratorOptions
		{
			ExistingTypes = new Dictionary<string, CppTypeSpelling>(StringComparer.Ordinal)
			{
				["ForceMagnitude"] = new("holo::Newtons", "holotype/core/units.hpp"),
			},
		});

		Assert.DoesNotContain("ForceMagnitude.gen.hpp", files.Keys);
		Assert.Contains("EntityId.gen.hpp", files.Keys);
	}

	private static IReadOnlyDictionary<string, string> Generate() => Generate(new CppGeneratorOptions());

	private static IReadOnlyDictionary<string, string> Generate(CppGeneratorOptions options)
	{
		Models.Schema schema = ExemplarSchema();
		return new CppCodeGenerator(options).Generate(schema, schema.GetCodeGenerator("Cpp".As<CodeGeneratorName>())!);
	}

	/// <summary>
	/// The schema a person would write to get the document's second section: an identifier over a
	/// number, and the refinement pair that shows the asymmetry.
	/// </summary>
	private static Models.Schema ExemplarSchema()
	{
		Models.Schema schema = new();

		SchemaCodeGenerator configuration = schema.AddCodeGenerator("Cpp".As<CodeGeneratorName>())!;
		configuration.Language = CppCodeGenerator.LanguageId.As<LanguageName>();
		configuration.Namespace = "holo".As<CodeNamespace>();

		SchemaSemanticType entity = schema.AddSemanticType("EntityId".As<SemanticTypeName>())!;
		entity.SetUnderlyingType(new Long());
		entity.Description = "A live entity. Distinct from every other identifier stored as a number.".As<SchemaChildDescription>();

		SchemaSemanticType force = schema.AddSemanticType("ForceMagnitude".As<SemanticTypeName>())!;
		force.SetUnderlyingType(new Float());
		force.Description = "The magnitude of a force.".As<SchemaChildDescription>();
		force.Unit = "N".As<Models.Metadata.UnitSymbol>();

		SchemaSemanticType weight = schema.AddSemanticType("Weight".As<SemanticTypeName>())!;
		weight.SetUnderlyingType(new Semantic { SemanticTypeName = "ForceMagnitude".As<SemanticTypeName>() });
		weight.Description = "What gravity pulls with.".As<SchemaChildDescription>();

		return schema;
	}
}
