// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Generation;

using ktsu.CodeBlocker;
using ktsu.Schema.Models;
using ktsu.Schema.Models.Names;
using ktsu.Schema.Models.Types;

/// <summary>
/// Emits C# POCOs for a schema's classes and enums.
/// </summary>
/// <remarks>
/// The type mapping is the exact inverse of the one <see cref="Models.Schema.AddClass(Type)"/>
/// uses to import CLR types, so generating from a schema and reimporting the result reproduces
/// the schema it started from. That round trip is what keeps the two mappings honest, and it is
/// covered by a test that compiles the generated source and reimports the compiled types.
/// </remarks>
public sealed class CSharpCodeGenerator : ISchemaCodeGenerator
{
	/// <summary>
	/// The language id this generator answers to.
	/// </summary>
	public const string LanguageId = LanguageName.CSharpName;

	/// <inheritdoc />
	public string Language => LanguageId;

	/// <inheritdoc />
	public IReadOnlyDictionary<string, string> Generate(Models.Schema schema, SchemaCodeGenerator configuration)
	{
		Ensure.NotNull(schema);
		Ensure.NotNull(configuration);

		Dictionary<string, string> files = [];

		foreach (SchemaEnum schemaEnum in schema.Enums)
		{
			files[$"{schemaEnum.Name}.g.cs"] = GenerateEnum(schemaEnum, configuration.Namespace);
		}

		foreach (SchemaClass schemaClass in schema.Classes)
		{
			files[$"{schemaClass.Name}.g.cs"] = GenerateClass(schemaClass, configuration.Namespace);
		}

		return files;
	}

	private static string GenerateEnum(SchemaEnum schemaEnum, CodeNamespace codeNamespace)
	{
		using CodeBlocker code = CodeBlocker.Create();
		WriteHeader(code, codeNamespace);

		WriteDocComment(code, schemaEnum.Description);
		code.WriteLine($"public enum {schemaEnum.Name}");
		using (new Scope(code))
		{
			foreach (EnumValueName value in schemaEnum.Values)
			{
				code.WriteLine($"{value},");
			}
		}

		return code.ToString();
	}

	private static string GenerateClass(SchemaClass schemaClass, CodeNamespace codeNamespace)
	{
		using CodeBlocker code = CodeBlocker.Create();
		WriteHeader(code, codeNamespace);

		WriteDocComment(code, schemaClass.Description);
		code.WriteLine($"public class {schemaClass.Name}");
		using (new Scope(code))
		{
			bool first = true;
			foreach (SchemaMember member in schemaClass.Members)
			{
				if (!first)
				{
					code.NewLine();
				}

				first = false;

				WriteDocComment(code, member.Description);
				WriteSchemaKeyAttribute(code, member.Type);
				code.WriteLine($"public {MapType(member.Type)} {member.Name} {{ get; set; }}{InitialiserFor(member.Type)}");
			}
		}

		return code.ToString();
	}

	private static void WriteHeader(CodeBlocker code, CodeNamespace codeNamespace)
	{
		code.WriteLine("// <auto-generated>");
		code.WriteLine("//     Generated from a .schema.json file by ktsu.Schema. Edits will be lost.");
		code.WriteLine("// </auto-generated>");
		code.NewLine();
		code.WriteLine("#nullable enable");
		code.NewLine();

		if (!string.IsNullOrEmpty(codeNamespace))
		{
			// File-scoped, so the body below needs no extra indentation.
			code.WriteLine($"namespace {codeNamespace};");
			code.NewLine();
		}
	}

	/// <summary>
	/// Writes a description out as an XML doc comment, which is the whole reason descriptions are
	/// carried on every element.
	/// </summary>
	private static void WriteDocComment(CodeBlocker code, string description)
	{
		if (string.IsNullOrEmpty(description))
		{
			return;
		}

		code.WriteLine("/// <summary>");
		foreach (string line in description.Split('\n'))
		{
			code.WriteLine($"/// {Escape(line.TrimEnd('\r'))}");
		}

		code.WriteLine("/// </summary>");
	}

	/// <summary>
	/// Records a keyed map's key member on the generated property.
	/// </summary>
	/// <remarks>
	/// The emitted dictionary type says what the key is but not where it comes from, so without
	/// this the schema could not be reconstructed from the generated code.
	/// </remarks>
	private static void WriteSchemaKeyAttribute(CodeBlocker code, BaseType type)
	{
		if (type is Models.Types.Array arrayType &&
			string.Equals(arrayType.Container, ContainerName.MapName, StringComparison.Ordinal) &&
			!string.IsNullOrEmpty(arrayType.Key))
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaKey(\"{arrayType.Key}\")]");
		}
	}

	private static string Escape(string text) =>
		text.Replace("&", "&amp;", StringComparison.Ordinal)
			.Replace("<", "&lt;", StringComparison.Ordinal)
			.Replace(">", "&gt;", StringComparison.Ordinal);

	/// <summary>
	/// Maps a schema type to the C# type that represents it.
	/// </summary>
	/// <remarks>
	/// Every case here has a counterpart in the import mapping, and the round-trip test fails if
	/// one of them drifts.
	/// </remarks>
	private static string MapType(BaseType type) => type switch
	{
		Bool => "bool",
		Int => "int",
		Long => "long",
		Float => "float",
		Double => "double",
		Models.Types.String => "string",
		Models.Types.DateTime => "System.DateTime",
		Models.Types.TimeSpan => "System.TimeSpan",

		// The colours before their vector bases: ColorRGB derives from Vector3.
		ColorRGB => "ktsu.Schema.Runtime.ColorRgb",
		ColorRGBA => "ktsu.Schema.Runtime.ColorRgba",
		Vector2 => "System.Numerics.Vector2",
		Vector3 => "System.Numerics.Vector3",
		Vector4 => "System.Numerics.Vector4",

		Models.Types.Enum enumType => enumType.EnumName,
		Models.Types.Object objectType => objectType.ClassName,
		Models.Types.Array arrayType => MapArray(arrayType),

		// A member left as None is reported by validation as a warning, not an error, so
		// generation is not refused for it. object keeps the output compiling.
		None => "object?",
		_ => "object?",
	};

	private static string MapArray(Models.Types.Array arrayType)
	{
		string elementType = MapType(arrayType.ElementType);

		if (!string.Equals(arrayType.Container, ContainerName.MapName, StringComparison.Ordinal))
		{
			// vector, and any container a consumer has invented, is a sequence.
			return $"System.Collections.Generic.List<{elementType}>";
		}

		return $"System.Collections.Generic.Dictionary<{MapKeyType(arrayType)}, {elementType}>";
	}

	/// <summary>
	/// Gets the C# type of a map's key, taken from the member the array keys on.
	/// </summary>
	/// <remarks>
	/// Validation guarantees a keyed map names a primitive member of its element class, so this
	/// only falls back when the schema is one validation would have refused generation for.
	/// </remarks>
	private static string MapKeyType(Models.Types.Array arrayType)
	{
		if (arrayType.TryGetKeyMember(out SchemaMember? keyMember) && keyMember is not null)
		{
			return MapType(keyMember.Type);
		}

		return "string";
	}

	/// <summary>
	/// Gets the initialiser a property needs to satisfy nullable reference analysis.
	/// </summary>
	private static string InitialiserFor(BaseType type) => type switch
	{
		Models.Types.String => " = string.Empty;",
		Models.Types.Array => $" = new {MapArrayInitialiser(type)}();",
		Models.Types.Object objectType => $" = new {objectType.ClassName}();",
		_ => string.Empty,
	};

	private static string MapArrayInitialiser(BaseType type) =>
		type is Models.Types.Array arrayType ? MapArray(arrayType) : string.Empty;
}
