// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Generation;

using System.Globalization;

using ktsu.CodeBlocker;
using ktsu.Schema.Models;
using ktsu.Schema.Models.Metadata;
using ktsu.Schema.Models.Names;
using ktsu.Schema.Models.Types;

/// <summary>
/// Emits C# POCOs for a schema's classes and enums.
/// </summary>
/// <remarks>
/// The type mapping is the exact inverse of the one <see cref="Models.Schema.AddClass(Type)"/>
/// uses to import CLR types, so generating from a schema and reimporting the result reproduces
/// the schema it started from. That round trip is what keeps the two mappings honest, and it is
/// covered by a test that compiles the generated source and reimports the compiled types.
/// </remarks>
public sealed class CSharpCodeGenerator : ISchemaCodeGenerator
{
	/// <summary>
	/// The language id this generator answers to.
	/// </summary>
	public const string LanguageId = LanguageName.CSharpName;

	/// <inheritdoc />
	public string Language => LanguageId;

	/// <inheritdoc />
	public IReadOnlyDictionary<string, string> Generate(Models.Schema schema, SchemaCodeGenerator configuration)
	{
		Ensure.NotNull(schema);
		Ensure.NotNull(configuration);

		Dictionary<string, string> files = [];

		foreach (SchemaEnum schemaEnum in schema.Enums)
		{
			files[$"{schemaEnum.Name}.g.cs"] = GenerateEnum(schemaEnum, configuration.Namespace);
		}

		foreach (SchemaClass schemaClass in schema.Classes)
		{
			files[$"{schemaClass.Name}.g.cs"] = GenerateClass(schemaClass, configuration.Namespace);
		}

		return files;
	}

	private static string GenerateEnum(SchemaEnum schemaEnum, CodeNamespace codeNamespace)
	{
		using CodeBlocker code = CodeBlocker.Create();
		WriteHeader(code, codeNamespace);

		WriteDocComment(code, schemaEnum.Description);
		code.WriteLine($"public enum {CSharpKeywords.Identifier(schemaEnum.Name)}");
		using (new Scope(code))
		{
			foreach (EnumValueName value in schemaEnum.Values)
			{
				code.WriteLine($"{CSharpKeywords.Identifier(value)},");
			}
		}

		return code.ToString();
	}

	private static string GenerateClass(SchemaClass schemaClass, CodeNamespace codeNamespace)
	{
		using CodeBlocker code = CodeBlocker.Create();
		WriteHeader(code, codeNamespace);

		WriteDocComment(code, schemaClass.Description);

		if (schemaClass.TravelsAsBytes)
		{
			code.WriteLine("[ktsu.Schema.Runtime.SchemaTravelsAsBytes]");
		}

		code.WriteLine($"public class {CSharpKeywords.Identifier(schemaClass.Name)}");
		using (new Scope(code))
		{
			bool first = true;
			foreach (SchemaMember member in schemaClass.Members)
			{
				if (!first)
				{
					code.NewLine();
				}

				first = false;

				WriteDocComment(code, member.Description);
				WriteSchemaKeyAttribute(code, member.Type);
				WriteMetadataAttributes(code, member);
				code.WriteLine($"public {MapType(member.Type)} {CSharpKeywords.Identifier(member.Name)} {{ get; set; }}{InitialiserFor(member)}");
			}
		}

		return code.ToString();
	}

	private static void WriteHeader(CodeBlocker code, CodeNamespace codeNamespace)
	{
		code.WriteLine("// <auto-generated>");
		code.WriteLine("//     Generated from a .schema.json file by ktsu.Schema. Edits will be lost.");
		code.WriteLine("// </auto-generated>");
		code.NewLine();
		code.WriteLine("#nullable enable");
		code.NewLine();

		if (!string.IsNullOrEmpty(codeNamespace))
		{
			// File-scoped, so the body below needs no extra indentation.
			code.WriteLine($"namespace {codeNamespace};");
			code.NewLine();
		}
	}

	/// <summary>
	/// Writes a description out as an XML doc comment, which is the whole reason descriptions are
	/// carried on every element.
	/// </summary>
	private static void WriteDocComment(CodeBlocker code, string description)
	{
		if (string.IsNullOrEmpty(description))
		{
			return;
		}

		code.WriteLine("/// <summary>");
		foreach (string line in description.Split('\n'))
		{
			code.WriteLine($"/// {Escape(line.TrimEnd('\r'))}");
		}

		code.WriteLine("/// </summary>");
	}

	/// <summary>
	/// Records a keyed map's key member on the generated property.
	/// </summary>
	/// <remarks>
	/// The emitted dictionary type says what the key is but not where it comes from, so without
	/// this the schema could not be reconstructed from the generated code.
	/// </remarks>
	private static void WriteSchemaKeyAttribute(CodeBlocker code, BaseType type)
	{
		if (type is Models.Types.Array arrayType &&
			string.Equals(arrayType.Container, ContainerName.MapName, StringComparison.Ordinal) &&
			!string.IsNullOrEmpty(arrayType.Key))
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaKey(\"{arrayType.Key}\")]");
		}
	}

	/// <summary>
	/// Records a member's semantic metadata on the generated property.
	/// </summary>
	/// <remarks>
	/// A C# type says what a value is and nothing about what it means, so without these the unit,
	/// range, default, interpolation and network encoding would be dropped by the reimport the
	/// round trip is built on - the same problem <see cref="WriteSchemaKeyAttribute"/> solves for
	/// a keyed map.
	/// </remarks>
	private static void WriteMetadataAttributes(CodeBlocker code, SchemaMember member)
	{
		if (member.Unit is not null)
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaUnit({Quote(member.Unit)})]");
		}

		if (member.Range is MemberRange range)
		{
			string wrap = range.Wrap ? ", Wrap = true" : string.Empty;
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaRange({Literal(range.Minimum)}, {Literal(range.Maximum)}{wrap})]");
		}

		if (DefaultArgument(member.DefaultValue) is string argument)
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaDefault({argument})]");
		}

		if (member.Interpolation is not Interpolation.None)
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaInterpolation(ktsu.Schema.Models.Metadata.Interpolation.{member.Interpolation})]");
		}

		if (member.Network is MemberNetwork network)
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaNetwork({Literal(network.Quantise)}, {(network.Delta ? "true" : "false")})]");
		}

		if (member.Editor is not null)
		{
			code.WriteLine($"[ktsu.Schema.Runtime.SchemaEditorHint({Quote(member.Editor)})]");
		}
	}

	/// <summary>
	/// Writes a default as the argument that binds the right <c>SchemaDefault</c> constructor.
	/// </summary>
	/// <returns>The argument text, or null when the member has no default.</returns>
	private static string? DefaultArgument(MemberDefault? value) => value switch
	{
		NumberDefault number => Literal(number.Value),
		BooleanDefault boolean => boolean.Value ? "true" : "false",
		TextDefault text => Quote(text.Value),
		_ => null,
	};

	/// <summary>
	/// Writes a double as a C# literal of type <see cref="double"/>.
	/// </summary>
	/// <remarks>
	/// The <c>D</c> suffix is what picks the double overload of <c>SchemaDefault</c> rather than
	/// the one taking a bool or a string, and round-trip formatting is what keeps the value the
	/// schema holds - a bound written back one bit short is a range that no longer contains what
	/// it used to. Invariant, because a machine writing a decimal comma would emit source that
	/// does not compile.
	/// </remarks>
	private static string Literal(double value) => value switch
	{
		double.PositiveInfinity => "double.PositiveInfinity",
		double.NegativeInfinity => "double.NegativeInfinity",
		_ when double.IsNaN(value) => "double.NaN",
		_ => $"{value.ToString("R", CultureInfo.InvariantCulture)}D",
	};

	/// <summary>
	/// Writes text as a C# string literal.
	/// </summary>
	private static string Quote(string text) =>
		$"\"{text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";

	private static string Escape(string text) =>
		text.Replace("&", "&amp;", StringComparison.Ordinal)
			.Replace("<", "&lt;", StringComparison.Ordinal)
			.Replace(">", "&gt;", StringComparison.Ordinal);

	/// <summary>
	/// Maps a schema type to the C# type that represents it.
	/// </summary>
	/// <remarks>
	/// Every case here has a counterpart in the import mapping, and the round-trip test fails if
	/// one of them drifts.
	/// </remarks>
	private static string MapType(BaseType type) => type switch
	{
		Bool => "bool",
		Int => "int",
		Long => "long",
		Float => "float",
		Double => "double",
		Models.Types.String => "string",
		Models.Types.DateTime => "System.DateTime",
		Models.Types.TimeSpan => "System.TimeSpan",

		// The colours before their vector bases: ColorRGB derives from Vector3.
		ColorRGB => "ktsu.Schema.Runtime.ColorRgb",
		ColorRGBA => "ktsu.Schema.Runtime.ColorRgba",

		// System.Numerics vectors hold floats and nothing else, so they represent a vector of
		// floats and only that. A vector of anything else falls through to the same object? every
		// other type this generator cannot yet say does, rather than being emitted as a type it
		// is not.
		Vector2 { ElementType: Float } => "System.Numerics.Vector2",
		Vector3 { ElementType: Float } => "System.Numerics.Vector3",
		Vector4 { ElementType: Float } => "System.Numerics.Vector4",

		Models.Types.Enum enumType => CSharpKeywords.Identifier(enumType.EnumName),
		Models.Types.Object objectType => CSharpKeywords.Identifier(objectType.ClassName),
		Models.Types.Array arrayType => MapArray(arrayType),

		// A member left as None is reported by validation as a warning, not an error, so
		// generation is not refused for it. object keeps the output compiling.
		None => "object?",
		_ => "object?",
	};

	private static string MapArray(Models.Types.Array arrayType)
	{
		string elementType = MapType(arrayType.ElementType);

		if (!string.Equals(arrayType.Container, ContainerName.MapName, StringComparison.Ordinal))
		{
			// vector, and any container a consumer has invented, is a sequence.
			return $"System.Collections.Generic.List<{elementType}>";
		}

		return $"System.Collections.Generic.Dictionary<{MapKeyType(arrayType)}, {elementType}>";
	}

	/// <summary>
	/// Gets the C# type of a map's key, taken from the member the array keys on.
	/// </summary>
	/// <remarks>
	/// Validation guarantees a keyed map names a primitive member of its element class, so this
	/// only falls back when the schema is one validation would have refused generation for.
	/// </remarks>
	private static string MapKeyType(Models.Types.Array arrayType)
	{
		if (arrayType.TryGetKeyMember(out SchemaMember? keyMember) && keyMember is not null)
		{
			return MapType(keyMember.Type);
		}

		return "string";
	}

	/// <summary>
	/// Gets the initialiser a property is given: the member's default when it has one, and
	/// otherwise whatever nullable reference analysis needs.
	/// </summary>
	/// <remarks>
	/// A default that is only recorded in an attribute is a default in name only - an instance of
	/// the generated type would still start at zero. The attribute is what lets the default be
	/// read back; this is what makes it true of the object.
	/// </remarks>
	private static string InitialiserFor(SchemaMember member) =>
		DefaultInitialiserFor(member) ?? member.Type switch
		{
			Models.Types.String => " = string.Empty;",
			Models.Types.Array arrayType => $" = new {MapArray(arrayType)}();",
			Models.Types.Object objectType => $" = new {CSharpKeywords.Identifier(objectType.ClassName)}();",
			_ => string.Empty,
		};

	/// <summary>
	/// Gets the initialiser for a member's default, or null when it has none that fits.
	/// </summary>
	/// <remarks>
	/// A default of a kind the member cannot hold is a validation error, and generation is refused
	/// for a schema that has one - so the mismatched cases here are only reachable by calling this
	/// generator directly on a schema that was never validated. They fall through to the type's
	/// own initialiser rather than emitting source that does not compile.
	/// </remarks>
	private static string? DefaultInitialiserFor(SchemaMember member) => (member.DefaultValue, member.Type) switch
	{
		(NumberDefault number, Int) => $" = {(long)number.Value};",
		(NumberDefault number, Long) => $" = {(long)number.Value}L;",
		(NumberDefault number, Float) when !double.IsFinite(number.Value) => $" = float.{NonFinite(number.Value)};",
		(NumberDefault number, Double) when !double.IsFinite(number.Value) => $" = double.{NonFinite(number.Value)};",
		(NumberDefault number, Float) => $" = {number.Value.ToString("R", CultureInfo.InvariantCulture)}f;",
		(NumberDefault number, Double) => $" = {Literal(number.Value)};",
		(BooleanDefault boolean, Bool) => $" = {(boolean.Value ? "true" : "false")};",
		(TextDefault text, Models.Types.String) => $" = {Quote(text.Value)};",
		(TextDefault text, Models.Types.Enum enumType) => $" = {CSharpKeywords.Identifier(enumType.EnumName)}.{CSharpKeywords.Identifier(text.Value)};",
		_ => null,
	};

	/// <summary>
	/// Names one of the two values a floating-point number can hold that has no literal.
	/// </summary>
	/// <remarks>
	/// The C++ generator refuses these, because C++ can only reach them through
	/// <c>&lt;limits&gt;</c> and a generated header quietly growing an include to write a default
	/// nobody meant is worse than being told. C# has them as named members of the type itself, so
	/// there is nothing to refuse: writing <c>NaNf</c>, which is what the round-trip form gave, was
	/// the only problem.
	/// </remarks>
	/// <param name="value">The value.</param>
	/// <returns>The member's name.</returns>
	/// <remarks>
	/// Guards rather than the constant patterns this would otherwise read as, because a pattern
	/// matches by equality and <see cref="double.NaN"/> is not equal to itself - so <c>double.NaN
	/// =&gt; "NaN"</c> is an arm that can never be taken, and the one value most likely to reach
	/// here would fall through to the last one.
	/// </remarks>
	private static string NonFinite(double value) => value switch
	{
		_ when double.IsNaN(value) => "NaN",
		_ when double.IsPositiveInfinity(value) => "PositiveInfinity",
		_ => "NegativeInfinity",
	};

}
