// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Schema.Cpp;

using ktsu.Coder.Ast;
using ktsu.Schema.Models;
using ktsu.Schema.Models.Metadata;
using ktsu.Semantics.Quantities;

using SchemaEnumType = ktsu.Schema.Models.Types.Enum;

/// <summary>
/// Builds the table that lets a program read a generated class without being written against it.
/// </summary>
/// <remarks>
/// A schema says a great deal that C++ cannot: a unit, a range, whether two states of a member can
/// be blended, how it should be quantised on the wire, what an editor should draw for it. The
/// generated header says all of it in comments, which is to say it says none of it. This is where
/// those facts become data.
/// <para>
/// <b>The offsets are not computed here.</b> The table says <c>offsetof(Class, member)</c>, so the
/// offset is whatever the compiler chose for that target, that ABI, those packing rules. A
/// generator that worked them out itself would be a second implementation of the C++ ABI and would
/// be wrong somewhere eventually. The same goes for <c>sizeof</c> and <c>alignof</c>.
/// </para>
/// <para>
/// <b>What reads it is written once, by hand.</b> A validator, a serialiser, a network codec and an
/// editor all walk this rather than each being a generator with its own copy of the same facts —
/// which is also what lets them work on a schema loaded at run time, where generated code cannot.
/// The rule that suggests: generate what has to be a <em>type</em>, and write by hand what only
/// needs to <em>read</em> a type's description.
/// </para>
/// </remarks>
/// <param name="schema">The schema being generated.</param>
/// <param name="configuration">The generator configuration, which names the namespace.</param>
/// <param name="options">What the target says about the types this generator cannot invent.</param>
internal sealed class CppReflectionBuilder(Models.Schema schema, SchemaCodeGenerator configuration, CppGeneratorOptions options)
{
	/// <summary>The axes of <c>Dimension</c>, in the order it declares them.</summary>
	/// <remarks>
	/// The keys <c>ktsu.Semantics.Quantities</c> writes in a dimensional formula, which is where
	/// these numbers come from: the member names a unit, the registry resolves it, and the unit
	/// knows its own dimension. A generated table therefore cannot disagree with the unit the
	/// schema wrote, because it is derived from it rather than restated beside it.
	/// </remarks>
	private static readonly string[] Axes =
	[
		"length", "mass", "time", "angle", "electricCurrent", "temperature", "amountOfSubstance", "luminousIntensity",
	];

	/// <summary>
	/// Builds the header carrying every class's table and the descriptor that anchors it.
	/// </summary>
	/// <returns>The file.</returns>
	public SourceFile Tables()
	{
		SourceFile file = new(CppReflection.TablesHeader) { IsHeader = true };

		file.HeaderComment.Add($"Generated by {options.GeneratedBy}. Do not edit.");
		file.HeaderComment.Add(string.Empty);
		file.HeaderComment.Add("Editing this file is editing the wrong thing: it is derived from the schema,");
		file.HeaderComment.Add("and the next build overwrites it. Change the schema instead.");
		file.HeaderComment.Add(string.Empty);
		file.HeaderComment.Add("Every offset and size here is the compiler's answer rather than this generator's,");
		file.HeaderComment.Add("so the table cannot drift from the layout it describes.");

		// offsetof is <cstddef>'s, and the widths the table stores are <cstdint>'s. The standard
		// library first and the target's own after it, each sorted, which is the order the rest of
		// this generator's files are written in; an empty import is the group separator.
		file.Imports.Add("<cstddef>");
		file.Imports.Add("<cstdint>");
		file.Imports.Add(string.Empty);

		foreach (string header in Headers())
		{
			file.Imports.Add(header);
		}

		NamespaceDeclaration containing = new(Containing);

		foreach (SchemaClass schemaClass in schema.Classes)
		{
			foreach (AstNode node in Described(schemaClass))
			{
				containing.Members.Add(node);
			}
		}

		containing.Members.Add(Everything());
		file.Members.Add(containing);
		return file;
	}

	/// <summary>
	/// The namespace the vocabulary and the tables share, under the target's own.
	/// </summary>
	/// <remarks>
	/// Under it rather than beside it, so a target that generates two schemas into one namespace
	/// gets one vocabulary: the shipped header is the same bytes for every schema, and writing it
	/// twice into the same place is therefore harmless rather than a conflict.
	/// </remarks>
	private string Containing =>
		string.IsNullOrEmpty(configuration.Namespace)
			? CppReflection.Namespace
			: $"{configuration.Namespace}::{CppReflection.Namespace}";

	/// <summary>Spells a generated type's name as the table has to reach it, from inside the vocabulary's namespace.</summary>
	private string Qualified(string name) =>
		string.IsNullOrEmpty(configuration.Namespace) ? name : $"{configuration.Namespace}::{name}";

	/// <summary>
	/// The headers the table needs: the vocabulary it is written in, every class it describes, and
	/// any enum it names a value of.
	/// </summary>
	private SortedSet<string> Headers()
	{
		SortedSet<string> headers = [$"\"{CppReflection.Header}{options.HeaderExtension}\""];

		foreach (SchemaClass schemaClass in schema.Classes)
		{
			headers.Add($"\"{schemaClass.Name}{options.HeaderExtension}\"");

			foreach (SchemaEnum named in schemaClass.Members.Select(Enumerated).OfType<SchemaEnum>())
			{
				headers.Add($"\"{named.Name}{options.HeaderExtension}\"");
			}
		}

		return headers;
	}

	/// <summary>
	/// One class: the values of any enum it names, its members, and the descriptor that attaches
	/// the two to the type.
	/// </summary>
	private IEnumerable<AstNode> Described(SchemaClass schemaClass)
	{
		string name = CppNaming.Type(schemaClass.Name.ToString(), "Class");

		foreach ((SchemaMember member, SchemaEnum named) in Enumerations(schemaClass))
		{
			yield return Values(schemaClass, member, named);
		}

		yield return Members(schemaClass);
		yield return Descriptor(schemaClass, name);
	}

	/// <summary>
	/// The names and numbers of one enum-typed member's values.
	/// </summary>
	/// <remarks>
	/// The number is read back out of the generated C++ enum rather than assumed to be the index.
	/// They are the same today, because the generated enumeration writes no explicit values; the
	/// moment it does, this keeps describing what is true rather than what used to be.
	/// </remarks>
	private FieldDeclaration Values(SchemaClass schemaClass, SchemaMember member, SchemaEnum named)
	{
		string type = Qualified(CppNaming.Type(named.Name.ToString(), "Enum"));
		ConstructionExpression values = new();

		foreach (string value in named.Values.Select(value => value.ToString()))
		{
			ConstructionExpression entry = new();
			entry.Arguments.Add(new MemberInitialiser("name", new LiteralExpression<string>(value)));
			entry.Arguments.Add(new MemberInitialiser(
				"value",
				new VariableReference($"static_cast<std::int64_t>({type}::{CppNaming.Type(value, "Enum value")})")));

			values.Arguments.Add(entry);
		}

		return Table(ValuesTable(schemaClass, member), "EnumValue", values);
	}

	/// <summary>Every member of one class, in declaration order, which is the order they are laid out in.</summary>
	private FieldDeclaration Members(SchemaClass schemaClass)
	{
		ConstructionExpression members = new();

		foreach (SchemaMember member in schemaClass.Members)
		{
			members.Arguments.Add(Described(schemaClass, member));
		}

		return Table($"k{schemaClass.Name}Members", "MemberInfo", members);
	}

	/// <summary>
	/// One member, with every property written out including the ones taking their default.
	/// </summary>
	/// <remarks>
	/// Omitting a default is what a person writing this by hand would do, and it is wrong here:
	/// designated initialisers with gaps trip <c>-Wmissing-field-initializers</c>, and generated
	/// code that needs a warning suppressed around it is generated code that does not survive a
	/// build stricter than the one it was written against.
	/// </remarks>
	private ConstructionExpression Described(SchemaClass schemaClass, SchemaMember member)
	{
		string owner = Qualified(CppNaming.Type(schemaClass.Name.ToString(), "Class"));
		string field = CppNaming.Member(member.Name.ToString(), options.MemberNaming, "Member");

		ConstructionExpression described = new();
		described.Arguments.Add(new MemberInitialiser("name", new LiteralExpression<string>(member.Name.ToString())));
		described.Arguments.Add(new MemberInitialiser("description", new LiteralExpression<string>(member.Description.ToString())));
		described.Arguments.Add(new MemberInitialiser("unit", new LiteralExpression<string>(member.Unit?.ToString() ?? string.Empty)));
		described.Arguments.Add(new MemberInitialiser("kind", new VariableReference(CppReflection.Kind(member.Type))));
		described.Arguments.Add(new MemberInitialiser("representation", new VariableReference(CppReflection.Representation(member.Type))));
		described.Arguments.Add(new MemberInitialiser("dimension", Dimension(member)));

		// The compiler answers both of these. That is the whole reason the table cannot drift from
		// the layout it describes.
		described.Arguments.Add(new MemberInitialiser(
			"offset",
			new VariableReference($"static_cast<std::uint32_t>(offsetof({owner}, {field}))")));
		described.Arguments.Add(new MemberInitialiser(
			"size",
			new VariableReference($"static_cast<std::uint32_t>(sizeof({owner}::{field}))")));

		described.Arguments.Add(new MemberInitialiser("has_range", new LiteralExpression<bool>(member.Range is not null)));
		described.Arguments.Add(new MemberInitialiser("range", Range(member.Range)));
		described.Arguments.Add(new MemberInitialiser("interpolation", new VariableReference(CppReflection.Blend(member.Interpolation))));
		described.Arguments.Add(new MemberInitialiser("editor_hint", new LiteralExpression<string>(member.Editor?.ToString() ?? string.Empty)));
		described.Arguments.Add(new MemberInitialiser("has_network", new LiteralExpression<bool>(member.Network is not null)));
		described.Arguments.Add(new MemberInitialiser("network", Network(member.Network)));
		described.Arguments.Add(new MemberInitialiser("enum_values", EnumValues(schemaClass, member)));

		return described;
	}

	/// <summary>
	/// The exponents of the unit the member names, or all zeroes when it names none.
	/// </summary>
	/// <remarks>
	/// A member that measures nothing — an identifier, a name, a flag — is dimensionless, and so is
	/// a member whose unit does not resolve. The second is not silently the same as the first:
	/// <c>Schema.Validate</c> reports an unresolvable unit, so reaching here with one means the
	/// schema was generated without being validated first.
	/// </remarks>
	private static ConstructionExpression Dimension(SchemaMember member)
	{
		ConstructionExpression dimension = new();
		Dictionary<string, int> formula = member.TryResolveUnit(out IUnit? unit, out _) && unit is not null
			? unit.Dimension.DimensionalFormula
			: new Dictionary<string, int>(StringComparer.Ordinal);

		foreach (string axis in Axes)
		{
			dimension.Arguments.Add(new LiteralExpression<int>(formula.TryGetValue(axis, out int exponent) ? exponent : 0));
		}

		return dimension;
	}

	private static ConstructionExpression Range(MemberRange? range)
	{
		ConstructionExpression written = new();
		written.Arguments.Add(new LiteralExpression<double>(range?.Minimum ?? 0.0));
		written.Arguments.Add(new LiteralExpression<double>(range?.Maximum ?? 0.0));
		written.Arguments.Add(new LiteralExpression<bool>(range?.Wrap ?? false));
		return written;
	}

	private static ConstructionExpression Network(MemberNetwork? network)
	{
		ConstructionExpression written = new();
		written.Arguments.Add(new LiteralExpression<double>(network?.Quantise ?? 0.0));
		written.Arguments.Add(new LiteralExpression<bool>(network?.Delta ?? false));
		return written;
	}

	private Expression EnumValues(SchemaClass schemaClass, SchemaMember member) =>
		Enumerated(member) is null
			? new ConstructionExpression()
			: new VariableReference(ValuesTable(schemaClass, member));

	/// <summary>
	/// The descriptor: what makes the table reachable from the type rather than by convention.
	/// </summary>
	/// <remarks>
	/// A specialisation rather than a class named after its subject, because the alternative is
	/// that every consumer spells <c>Describe</c> plus the class's name for itself and nothing
	/// checks that it got it right. <c>describe&lt;RigidBody&gt;()</c> either finds a table or is a
	/// compile error naming the type that has none.
	/// </remarks>
	private ClassDeclaration Descriptor(SchemaClass schemaClass, string name)
	{
		ClassDeclaration describe = new("Describe")
		{
			Kind = TypeDeclarationKind.Struct,
			SpecialisationArguments = { new TypeReference(Qualified(name)) },
		};

		ConstructionExpression info = new();
		info.Arguments.Add(new MemberInitialiser("name", new LiteralExpression<string>(schemaClass.Name.ToString())));
		info.Arguments.Add(new MemberInitialiser("description", new LiteralExpression<string>(schemaClass.Description.ToString())));
		info.Arguments.Add(new MemberInitialiser(
			"size",
			new VariableReference($"static_cast<std::uint32_t>(sizeof({Qualified(name)}))")));
		info.Arguments.Add(new MemberInitialiser(
			"alignment",
			new VariableReference($"static_cast<std::uint32_t>(alignof({Qualified(name)}))")));
		info.Arguments.Add(new MemberInitialiser("travels_as_bytes", new LiteralExpression<bool>(schemaClass.TravelsAsBytes)));
		info.Arguments.Add(new MemberInitialiser("members", new VariableReference($"k{schemaClass.Name}Members")));

		describe.Members.Add(new FieldDeclaration("info", "ClassInfo")
		{
			IsStatic = true,
			IsConstant = true,
			InitialValue = info,
		});

		return describe;
	}

	/// <summary>
	/// Every class the schema declares, in declaration order, so a tool can walk them all without
	/// naming any of them.
	/// </summary>
	private FieldDeclaration Everything()
	{
		ConstructionExpression all = new();

		foreach (SchemaClass schemaClass in schema.Classes)
		{
			string name = Qualified(CppNaming.Type(schemaClass.Name.ToString(), "Class"));
			all.Arguments.Add(new VariableReference($"&Describe<{name}>::info"));
		}

		FieldDeclaration everything = new("kAll", new TypeReference("ClassInfo")
		{
			IsReadOnly = true,
			Indirection = TypeIndirection.Pointer,
			IsArray = true,
		})
		{
			IsConstant = true,
			InitialValue = all,
		};

		everything.Documentation.Add("Every class this schema declares, in declaration order.");
		return everything;
	}

	private static FieldDeclaration Table(string name, string type, ConstructionExpression entries)
	{
		FieldDeclaration table = new(name, new TypeReference(type) { IsArray = true })
		{
			IsConstant = true,
			InitialValue = entries,
		};

		return table;
	}

	private static string ValuesTable(SchemaClass schemaClass, SchemaMember member) =>
		$"k{schemaClass.Name}{member.Name}Values";

	/// <summary>The enum a member names, or null when it names none.</summary>
	private SchemaEnum? Enumerated(SchemaMember member) =>
		member.Type is SchemaEnumType named ? schema.GetEnum(named.EnumName) : null;

	/// <summary>
	/// Each member that names an enum, paired with the enum it names.
	/// </summary>
	/// <remarks>
	/// A projection rather than a loop with a test inside it: a member that names no enum
	/// contributes nothing, which is what an empty sequence says, and the caller then does one
	/// thing to everything it is handed.
	/// </remarks>
	private IEnumerable<(SchemaMember Member, SchemaEnum Named)> Enumerations(SchemaClass schemaClass) =>
		schemaClass.Members.SelectMany(member => Enumerated(member) is SchemaEnum named
			? new[] { (Member: member, Named: named) }
			: []);
}
